/** @type {import("@commitlint/types").UserConfig} */
module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
        "i18n",
        "payments",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "web",
        "api",
        "worker",
        "ui",
        "shared-types",
        "payments",
        "notifications",
        "i18n",
        "db",
        "auth",
        "cart",
        "checkout",
        "uniteller",
        "admin",
        "deps",
        "config",
        "ci",
        "release",
      ],
    ],
    "subject-case": [0],
    "header-max-length": [2, "always", 100],
  },
};
